sudo: required
services:
  - docker

language: go
go:
  - "1.x"
  - "1.10.x"

before_install:
  - make deps

script:
  - make test
  - make clean build

# deploy:
#   provider: script
#   script: make deploy
#   on:
#     branch: master
